'''
defines a template to report after all jobs get done
'''

class TemplateFinalReport(object):
	def __init__(self, token="", channel="random", mention=[]):
		self.token = token
		self.channel = channel
		self.mention = ", ".join(map(lambda s: "%20%40{}".format(s), mention)) if mention else ""

	def out(self):
		return self.template().format(token=self.token, channel=self.channel, mention=self.mention)

	@staticmethod
	def template():
		return """
#/bin/sh

########################################################
# This script is automatically generated by uge_cooker #
# For more info, https://github.com/otiai10/uge_cooker #
########################################################

#$ -S /bin/sh

TEXT="Hey{mention}, your jobs are all done! Check it out now!!"

curl -XPOST "https://slack.com/api/chat.postMessage" \
-d "token={token}" \
-d "channel={channel}" \
-d "link_names=1" \
-d "text=$TEXT"

"""[1:-1]
