'''
defines a template to sync all spawned jobs
'''

class TemplateSyncSpawn(object):
	def __init__(self, parent_name="PARENT", ids=[], sleep=20):
		self.parent_name = parent_name
		self.ids = ids
		self.sleep = sleep

	def out(self):
		ids = " ".join(map(lambda _id: "-e {}".format(_id), self.ids))
		return self.template().format(parent_name=self.parent_name, ids=ids, sleep=self.sleep, count=len(self.ids))

	@staticmethod
	def template():
		return """
#/bin/sh

########################################################
# This script is automatically generated by uge_cooker #
# For more info, https://github.com/otiai10/uge_cooker #
########################################################

#$ -S /bin/sh

while true
do
	sleep {sleep}
	found=`qstat | grep {ids}`
	if [ -z "$found" ]; then
		break
	fi
done
echo "All {count} jobs belonging to {parent_name} seem to be done: `date`"
echo "This sync-spawn script would finish. Bye!"

"""[1:-1]
